CREATE TABLE mview_refresh_log (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    mview_name   VARCHAR2(128),
    status       VARCHAR2(30),
    message      VARCHAR2(4000),
    log_time     DATE,
    CONSTRAINT check_status CHECK(status IN ('in progress', 'done', 'error'))
);
